### ISSUE TITLE
-wno-unused-return is not an option on g++ 

### ISSUE THREAD

**Issue by jeffeb3** [atom/node-oniguruma#25]
I'm using g++ version 4.3.4 (SUSE Linux)

I get this error (when built using node-gyp from the atom installer):
```
  CXX(target) Release/obj.target/onig_scanner/src/onig-cache.o
cc1plus: error: unrecognized command line option "-Wno-unused-result"
make: *** [Release/obj.target/onig_scanner/src/onig-cache.o] Error 1
make: Leaving directory `/lhome/eberlj/atom/node_modules/oniguruma/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```

According to this post, you should use -Wno-unused-value instead:
http://stackoverflow.com/questions/19464892/cc1plus-wno-unused-result-error

**Comment by kevinsawicki** [comment]
It does appear to be a gcc option:

```
-Wno-unused-result
Do not warn if a caller of a function marked with attribute warn_unused_result (see Function Attributes) does not use its return value. The default is -Wunused-result. 
```

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

Perhaps you are just using an older version where it isn't supported yet?

**Comment by jeffeb3** [comment]
You are right, it was added in 4.4 (according to hearsay on the Internet). I am using 4.3.4. If you felt like making it compatible with my gcc, here is a nice diff from another makefile:
http://repo.or.cz/w/tinycc.git/blobdiff/40a54c4399cc5e687d93add4b89bc16c19aaddfe..e79c3533ecefd004daad8a27333582b2dad7f0b0:/Makefile

Otherwise, I will wait until I get to upgrade to a post-2009 compiler. :) Stupid enterprise Linux.

**Comment by kevinsawicki** [comment]
Closing this out, gcc 4.4 will be a requirement of this library since it is 6 years old at this point.
