### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by joepie91** [atom/node-oniguruma#39]
The "more information" link in the README to http://www.geocities.jp/kosako3/oniguruma/doc/RE.txt is broken. [Here](https://web.archive.org/web/20150706054439/http://www.geocities.jp/kosako3/oniguruma/doc/RE.txt) is an archived version. It should probably be included in the repository itself...

**Comment by abe33** [comment]
I didn't your issue until now, but I submitted a PR for that (#42). And FWIW the whole oniguruma documentation can be found [here](http://oniguruma.rubyforge.org/oniguruma/).

**Comment by thomasjo** [comment]
Fixed in #42.
