### ISSUE TITLE
Support for Node 4 lost in latest minor release

### ISSUE THREAD

**Issue by jefflembeck** [atom/node-oniguruma#65]
https://github.com/atom/node-oniguruma/commit/80716271c26bfc02300d599f83b954676f892a48#diff-4cb512c0b8c044091a83b49d95f77ddcR1

With the addition of destructuring assignments, this only supports node 6 now.

**Comment by maxbrunsfeld** [comment]
Yup, we're generally embracing the ES6 features and assuming a recent Node version on our projects, but I'm open to a PR that adds Node 4 support back. 😕

**Comment by elingerojo** [comment]
@maxbrunsfeld 

On last commit of PR #66, I left the "removed" code as [commented code](https://github.com/elingerojo/node-oniguruma/blob/8a07e1377e71951f18fe90491800d4c77bde2077/src/oniguruma.js#L6-L52) for easy review but if you want, I can add another commit without the debris

**Comment by ashleygwilliams** [comment]
related: https://github.com/atom/node-oniguruma/pull/70

**Comment by Ben3eeE** [comment]
Closed via https://github.com/atom/node-oniguruma/pull/71
