### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by xxx** [atom/node-oniguruma#68]
The link to the Oniguruma flavor docs from http://atom.github.io/node-oniguruma/ is dead. Wayback Machine has it, but probably easiest to just link to `doc/RE` in the repo.

**Comment by bradennapier** [comment]
dont really know what that means but i can not find a single reference to any information about this RE -- the offical package does not even have a single link

the regexp is thus impossible to learn about using and is extremely upsetting trying to make simple changes to the darn undocumented grammars that atom uses

http://oniguruma.rubyforge.org/oniguruma/files/Syntax_txt.html 

gone

**Comment by bradennapier** [comment]
like wtf? is this from 1990?  it goes to some japanese geocities page? wtf? geocities still exists?

![image](https://user-images.githubusercontent.com/15365418/28154663-d7176a56-675f-11e7-9482-7f1d950554b8.png)

**Comment by xxx** [comment]
The document in question is at https://github.com/atom/node-oniguruma/blob/master/deps/onig/doc/RE

**Comment by jyn514** [comment]
I don't think the atom.io website is open-source; at least, I can't seem to find where it's hosted. I'd be happy to fix it up if you can show me where.

**Comment by jyn514** [comment]
@xxx Where should I link to? https://github.com/atom/node-oniguruma/blob/master/deps/onig/doc/RE appears to be the source for a webpage, but I can't find where it's hosted.

**Comment by xxx** [comment]
@jyn514 I don't understand what you're asking.

https://github.com/atom/node-oniguruma/blob/master/deps/onig/doc/RE is just a text file. It's also contained in the actual oniguruma repo at https://github.com/kkos/oniguruma/blob/master/doc/RE
