### ISSUE TITLE
VS path is hardcoded?

### ISSUE THREAD

**Issue by MikhailArkhipov** [atom/node-oniguruma#76]
`npm install oniguruma`

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

~\node_modules\oniguruma\build\oniguruma.vcxproj(20,3): 
error MSB4019: The imported project "C:\Program Files (x86)\Microsoft VisualStudio\Preview
\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props" was not found. 
Confirm that the path in the <Import> declaration is correct, 
and that the file exists on disk.
```

VS 2017 has multiple installs (I have 3). You can try and use https://github.com/Microsoft/vswhere for the location

**Comment by thomasjo** [comment]
Nothing is hard-coded. This is an upstream problem in [node-gyp](https://github.com/nodejs/node-gyp/issues/1056). Either install VS2015, or ensure you have recent version of npm (5.x or newer). Further details can be found in the upstream issue comments.
