### ISSUE TITLE
endPosition argument

### ISSUE THREAD

**Issue by Thom1729** [atom/node-oniguruma#79]
I'm using node-oniguruma to port the Sublime Text syntax highlighting engine to JavaScript. Sometimes, the engine has to restrict scanning to a prefix of the current line (because an `escape` pattern has been matched). In that situation, I am explicitly slicing the string. It would be better to instead pass an `endPosition` argument to `findNextMatchSync`. Oniguruma supports this, but node-oniguruma does not expose the feature, but always passes the end of the string as the end position.

**Comment by NeekSandhu** [comment]
Sounds totally amazing and would love to see it implemented.

I would love to bring this to [`node-oniguruma`'s WebAssembly port, onigasm](https://github.com/NeekSandhu/onigasm) once it's accepted here.

**Comment by rsese** [comment]
Thank you again for the suggestion; closing per the comment in https://github.com/atom/node-oniguruma/pull/90#issuecomment-481962225
